name: Build Plugin
on:
  push:
    tags: ['v*']
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build Plugin
      run: dotnet build plugin/FyteClub.csproj -c Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: plugin/bin/Release/FyteClub.dll